### ISSUE TITLE
goblins dig through standard protections mods

### ISSUE THREAD

**Issue by growlf** [FreeLikeGNU/goblins#1]
Both the "Areas" mod and the "Protector" block mods are completely ineffective against these beautiful little vermin - and I do not see any other way to fend off "special" areas that need to remain unscathed.  Players/admins will need/want to be able to safeguard certain areas from their wanton destruction.

**Comment by growlf** [comment]
I have forked this and would not mind working on a fix for it if you would like? (pull request as soon as I have a working solution)

**Comment by FreeLikeGNU** [comment]
Can you tell me what actions the mobs are doing and in what areas?  They should not spawn where protected according to the Mobs_Redo API.  
Check your minetest/minetest.conf for: 

`mobs_spawn_protected = false`

**Comment by growlf** [comment]
You are very correct on that bit - thank you.  However, they still seem to dig _into_ areas that are protected with both Areas and Protection blocks alike.  Have I maybe missed a doc on a setting that already exists for that one?

**Comment by FreeLikeGNU** [comment]
No, its something I forgot to consider for their custom digging and such... I have just pushed an update that should include a fix to keep them from messing with protected areas. Please let me know if this works for you.

**Comment by growlf** [comment]
Excellent - thank you!  I have pulled the fresh copy and ran a few tests as follows:
1) placed a hollow stone cube that is entirely within a protected area (using /areas mod) and left a goblin within it for a period of time (more than enough for it to decide to dig out) - and it never did (left it for over 10 minutes). (good so far)
2) placed another hollow cube around that, and let another digger loose in the in-between area - he almost immediately dug through the center cube (only the first 1xblock so far as I have seen) and then both of them flow out a hole they dug in the outer cube (rascally little buggers - I gotta give them credit for the escape there :) ) 
3) redid the setup with only the outer (unprotected) area being populated with a digger, and he has yet to touch the interior as it did in the first test...  some kind of coincidence?  or is there a form of cooperation that I am seeing?  Probably just my wishful thinking there.
4) I have now re-set and tested scenario 1, 7 more times.. and in all but 2 of the trials, they free each other and flee - leaving the remaining protected area alone!.  I gotta say.. I am almost linking this better than a logical-perfect fix! LOL    (consider leaving this as is, please :) )

**Comment by growlf** [comment]
One more test, of interest:
I placed a swarm of the goblins inside the protected hollow (1xblock thick stone - as before) cube, and waited for 5 mins - nothing happened.  Totally as desired - if I was imprisoning them *evil cackle* - then put some on the roof of it - they dug through almost immediately and became trapped with the others.  Seems they can dig _into_ a protected area exactly one block - and yup, I am ok with that, indeed.  I continue to test with the escapee scenario (a rescuer outside the protected zone with but one block between them that _is_ protected), and it is almost every time that they free the prisoners and flee.  Absolutely hilarious.  This is by far my fave mod in a while.  Thank you!

**Comment by FreeLikeGNU** [comment]
That must be because they only check if the block they are occupying is protected...  I could add a radius of influence setting to make this more secure should a player desire..

It also seems I left out a few checks for the dogs burying bones and/or consuming them in protected areas. This should be added in the next update.

Thanks for reporting and testing!

**Comment by growlf** [comment]
Ahh.  I had not tested the Gobdogs yet - I can totally see that.  Well, if you DO fix that check the rest of the way, I will be sad to see my little escapees lose their secret power - but I understand the desire to be complete and accurate with such things.

**Comment by FreeLikeGNU** [comment]
I pushed a release that should respect protection fully.  I have added a var
`local goblin_node_protect_strict = true`  in behaviors.lua that when false, will allow the goblins behave with some relaxations as you desired - they will only check the position they occupy for protection and may dig nodes in the bounds of their searches.

**Comment by growlf** [comment]
Awesome! Thank you :)  Looks good!
