### ISSUE TITLE
Crash if used together with minecart

### ISSUE THREAD

**Issue by rusty-snake** [FreeLikeGNU/goblins#10]
Great mod, Thanks.

---

I have discovered that there is an error when using this mod together with minecart.

**STR**
1. Install minetest (5.2.0)
2. Install this mod
3. Install [minecart](https://github.com/joe7575/minecart)
4. Create a new world (I used mapgen v7)
5. Enable goblins and minecart
6. Start the server/world
7. Wait a few seconds

**Actual behaviou** 

Server crash with error message:
```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'goblins' in callback luaentity_Step(): Invalid position (expected table got nil).
stack traceback:
        [C]: in function 'get_node'
        ...minetest/mods/00minemods-techage/minecart/protection.lua:45: in function 'is_protected'
        ...ion/.minetest/mods/00minemods-mobs/goblins/behaviors.lua:441: in function 'search_replace'
        ...minetest/mods/00minemods-mobs/goblins/goblins_custom.lua:29: in function 'do_custom'
        /home/user/.minetest/mods/00minemods-mobs/mobs/api.lua:3370: in function </home/user/.minetest/mods/00minemods-mobs/mobs/api.lua:3248>
stack traceback:
        [C]: in function 'get_node'
        ...minetest/mods/00minemods-techage/minecart/protection.lua:45: in function 'is_protected'
        ...ion/.minetest/mods/00minemods-mobs/goblins/behaviors.lua:441: in function 'search_replace'
        ...minetest/mods/00minemods-mobs/goblins/goblins_custom.lua:29: in function 'do_custom'
        /home/user/.minetest/mods/00minemods-mobs/mobs/api.lua:3370: in function </home/user/.minetest/mods/00minemods-mobs/mobs/api.lua:3248>
```

**expected behaviour**

No crash.

**unclear**

IDK which mod is the root cause.

**Comment by FreeLikeGNU** [comment]
Can you tell me what versions of mobs_redo, goblins and minecart you are using to help me track this down?  Thank you!

**Comment by rusty-snake** [comment]
I just downloaded the latest versions of all three from the contentDB and was able to reproduce. So at least the latest version in the contentDB are affected.

**Comment by FreeLikeGNU** [comment]
I think I tracked down the issue with my code, pull latest from here or contentDB.  Please let me know if this works for you and thanks for the report!

**Comment by rusty-snake** [comment]
works! :100: 

OT: Is there any reason why mossy_cobblestone has a light-level? Is this a workaround for something?

**Comment by FreeLikeGNU** [comment]
> OT: Is there any reason why mossy_cobblestone has a light-level? Is this a workaround for something?

Lore: The mossy cobble glow attracts goblins who find the moss conducive to growing their fungus.  It has some other odd effects on goblins as well...
  
Technically: the glow of the mossycobble is just to balance them stealing your torches (so you are not so often left in complete darkness)

If it breaks the game for folks, I can make the glow something optional..

**Comment by rusty-snake** [comment]
It sometimes looks a bit strange. 

![Screenshot_2020-06-29_18-26-15-fs8](https://user-images.githubusercontent.com/41237666/86031553-823fd880-ba25-11ea-92db-f8fabf2cde7f.png)

hard transition

![Screenshot_2020-06-29_18-27-15-fs8](https://user-images.githubusercontent.com/41237666/86031570-87048c80-ba25-11ea-8ff3-12d83c01fad1.png)

the block above the torch id darker the the blocks future away of the torch. Even they have the same colour range (ignoring the green).

> so you are not so often left in complete darkness

I just had to think of a kind of `goblins:goblin_torch` and a goblin who is placing them. like [maidroid torch core](https://github.com/tacigar/maidroid).

**Comment by FreeLikeGNU** [comment]
the update next week will have a solution for the mossy cobblestone.
