### ISSUE TITLE
Use bones from the bonemeal mod?

### ISSUE THREAD

**Issue by orbea** [FreeLikeGNU/goblins#2]
I noticed that there are goblins have their own bones and if the bonemeal mod is also used, the player now has access to two different kinds of bones. Perhaps goblins can optionally support the bonemeal mod if its installed?

https://notabug.org/TenPlus1/bonemeal

**Comment by FreeLikeGNU** [comment]
What would you have in mind for support?  Replacing the goblins mod bones with those of bonemeal if that mod is active or ???
