### ISSUE TITLE
Add maxlight and minlight to the goblin mobs

### ISSUE THREAD

**Issue by orbea** [FreeLikeGNU/goblins#3]
The mobs are missing maxlight/minlight and now spawn all over the place in well light underground constructions.

The mobs from mobs_monster do not have this problem.

**Comment by orbea** [comment]
I read again the code again and see it does have `min_light` and `max_light`, but the `max_light` is a value of `50` which is far beyond the max of `15` (sunlight). I suggest it should be `10` at the very most (torch light).

Edit: And in the latest commit I see you lowered it to `14` for most of the mobs except for the hoarder which is still `50`.

**Comment by FreeLikeGNU** [comment]
Hoarder is a bit special, as they are attracted to the mossy cobble and chests found in dungeons, even near the surface.   Feel free to nerf them, but I wanted to have an element of danger in these areas.  I may tone down some other aspects or make them less aggressive if a player has befriended some number of goblins...

**Comment by FreeLikeGNU** [comment]
I've set all the goblins to spawn up to max_light = 10 as per your suggestion with [this commit](https://github.com/FreeLikeGNU/goblins/commit/8bc760780962d7a06449327cbda259c90d5027ed) All goblins ( except non-aggro gobdogs) should take damage from light above 14 as well.
